#!/bin/bash

# Make vim to the default editor
export ALTERNATE_EDITOR=""
export EDITOR="vim" # $EDITOR opens in terminal
# export VISUAL="emacsclient -nc -a emacs"         # $VISUAL opens in GUI mode

export TERMINAL="xterm"

export PROMPT_COMMAND='history -a'

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=50000000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoreboth:erasedups
# Make some commands not show up in history
export HISTIGNORE="ls:cd -:pwd:exit:date"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Always enable colored `grep` output
# export GREP_OPTIONS="--color=auto";

export WEBSITE=~/Projects/juev.org/content/posts

export LEDGER_FILE=~/Projects/Github/hledger/main.journal
